In [1]:
import numpy as np

class ANN:
    def __init__(self, input_size, hidden_layers, hidden_neurons, output_size, learning_rate):
        self.weights=[]
        self.bias=[]
        self.hidden_layers = hidden_layers
        self.learning_rate = learning_rate;
        
        for i in range(hidden_layers + 1):
            if i==0:
                self.weights.append(np.random.randn(hidden_neurons, input_size))
                self.bias.append(np.full((hidden_neurons, 1),1))
            elif i==hidden_layers:
                self.weights.append(np.random.randn(output_size, hidden_neurons))
                self.bias.append(np.full((output_size, 1),1))
            else:
                self.weights.append(np.random.randn(hidden_neurons, hidden_neurons))
                self.bias.append(np.full((hidden_neurons, 1),1))
    
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def first_order_sigmoid(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))
    
    def forward(self, x):
        activations = []
        activations.append(x)
        for i in range(self.hidden_layers + 1):
            x=np.dot(self.weights[i], activations[i]) + self.bias[i]
            activations.append(self.sigmoid(x))
        return activations
    
    def backward(self, activations, di, m):
        delta = (activations[-1] - di.T) * self.first_order_sigmoid(np.dot(self.weights[-1], activations[-2]) + self.bias[-1])
        for i in range(self.hidden_layers, -1, -1):
            if i==self.hidden_layers:
                prev=np.array(self.weights[i])
                self.weights[i] = self.weights[i] - (self.learning_rate/m) * np.dot(delta,activations[i].T)
                self.bias[i] = self.bias[i] - (self.learning_rate/m) * np.sum(delta, axis=1, keepdims=True)
            else:
                delta = np.dot(prev.T, delta) * self.first_order_sigmoid(np.dot(self.weights[i], activations[i]) + self.bias[i])
                prev = np.array(self.weights[i])
                self.weights[i] = self.weights[i] - (self.learning_rate/m) * np.dot(delta, activations[i].T)
                self.bias[i]= self.bias[i] - (self.learning_rate/m) * np.sum(delta, axis=1, keepdims=True)
                
    def train(self, x, y, epochs):
        for i in range(epochs):
            activations = self.forward(x)
            m = x.shape[1]
            self.backward(activations, y ,m)
            if(i%1000==0):
                print("Error at %d epoch : "%(i), np.sum(activations[-1] - y.T))
                
    def predict(self, x):
        predictions= []
        for input in x:
            prediction = self.forward(np.array(input))
            predictions.append(prediction[-1])
        return predictions

In [2]:
input_size = 4
hidden_layers = 2
neurons_in_hidden_layer = 5
output_size = 3
learning_rate = 0.1

model=ANN(input_size, hidden_layers, neurons_in_hidden_layer, output_size, learning_rate)

In [3]:
import pandas as pd
df=pd.read_csv('Iris.csv')
x=df.drop(['Id','Species'], axis=1)
y=df['Species']

In [4]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, encoded_labels, test_size=0.2, random_state=62)

from tensorflow.keras.utils import to_categorical

labels = np.array(y_train)
y_train = to_categorical(labels)
y_train = np.array(y_train)

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [5]:
x_train = x_train.values
x_train = np.array(x_train)
x_train = x_train.T
x_test = x_test.values

In [6]:
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1

In [7]:
epochs = 100000
model.train(x_train, y_train, epochs)

Error at 0 epoch :  114.79889995151545
Error at 1000 epoch :  8.332583394239949
Error at 2000 epoch :  8.871376504759901
Error at 3000 epoch :  7.322579757941519
Error at 4000 epoch :  6.3326672340094445
Error at 5000 epoch :  5.18378497724828
Error at 6000 epoch :  4.1738761777541935
Error at 7000 epoch :  3.454653849347544
Error at 8000 epoch :  2.961157669807525
Error at 9000 epoch :  2.6170641917732054
Error at 10000 epoch :  2.3660979905998385
Error at 11000 epoch :  2.1735670755469307
Error at 12000 epoch :  2.019737067699249
Error at 13000 epoch :  1.893210549689019
Error at 14000 epoch :  1.786945205103077
Error at 15000 epoch :  1.696259841244221
Error at 16000 epoch :  1.6178605803975472
Error at 17000 epoch :  1.5493368320988719
Error at 18000 epoch :  1.4888762245377936
Error at 19000 epoch :  1.4350891794746645
Error at 20000 epoch :  1.3868937237940058
Error at 21000 epoch :  1.343436389021532
Error at 22000 epoch :  1.304036234823309
Error at 23000 epoch :  1.26814439667

In [8]:
hh = model.forward([[6.7], [3.0], [5.2], [2.3]])
print(hh[-1])

[[0.00109345]
 [0.01163715]
 [0.99181231]]


In [9]:
test_sample = []
for i in x_test:
    test_sample.append([[x] for x in i.tolist()])

In [10]:
y_pred = model.predict(test_sample)
y_pred = np.hstack([np.argmax(arr, axis=0) for arr in y_pred]).flatten()

In [11]:
print(y_test)

[2 2 0 0 2 1 2 0 1 1 2 2 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]


In [12]:
print(y_pred)

[2 2 0 0 2 1 2 0 1 1 2 2 0 1 1 1 0 1 0 0 0 0 2 1 2 0 2 0 2 0]


In [13]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1score = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1score)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
